cc_library( 
    name = "hocon",
    srcs = glob(["src/*.cc", "src/nodes/*.cc", "src/values/*.cc",
                 "inc/internal/*.hpp", "inc/internal/nodes/*.hpp", "inc/internal/values/*.hpp"]),
    hdrs = glob(["inc/hocon/*.hpp", "inc/hocon/parser/*.hpp"]),
    includes = ["inc"]
)
